const elavations = [
  { elevation: -2, color: "blue" },
  { elevation: -1, color: "royalblue" },
  { elevation: 0, color: "deepskyblue" },
  { elevation: 1, color: "goldenrod" },
  { elevation: 2, color: "seagreen" },
  { elevation: 3, color: "green" },
  { elevation: 4, color: "yellow" },
  { elevation: 5, color: "orange" },
  { elevation: 6, color: "red" },
  { elevation: 7, color: "brown" },
  { elevation: 8, color: "darkred" },
  { elevation: 9, color: "saddlebrown" },
  { elevation: 10, color: "gray" },
]

// const elavations = [ // Another Option generated by github copilot ("create an array of 15 colors from dark blue, to yellow, to green, to brown in objects as colors with elevations from -2 to 10")
//   { color: '#00008B', elevation: -2 }, // Dark Blue
//   { color: '#0000CD', elevation: -1 },
//   { color: '#0000FF', elevation: 0 },
//   { color: '#1E90FF', elevation: 1 },
//   { color: '#00BFFF', elevation: 2 },
//   { color: '#87CEEB', elevation: 3 },
//   { color: '#FFFF00', elevation: 4 }, // Yellow
//   { color: '#ADFF2F', elevation: 5 },
//   { color: '#7FFF00', elevation: 6 },
//   { color: '#32CD32', elevation: 7 },
//   { color: '#228B22', elevation: 8 },
//   { color: '#006400', elevation: 9 }, // Green
//   { color: '#8B4513', elevation: 10 }, // Brown
//   { color: '#A0522D', elevation: 11 },
//   { color: '#D2691E', elevation: 12 }
// ];




