const hawaiiCounties = [
  { name: "Hawaii County", state: "Hawaii", type: "County", population: 204012 },
  { name: "Honolulu County", state: "Hawaii", type: "County", population: 978317 },
  { name: "Kalawao County", state: "Hawaii", type: "County", population: 81 },
  { name: "Kauai County", state: "Hawaii", type: "County", population: 73210 },
  { name: "Maui County", state: "Hawaii", type: "County", population: 167902 }
];

const alaskaBoroughsAndCensusAreas = [
  { name: "Aleutians East Borough", state: "Alaska", type: "Borough", population: 3419 },
  { name: "Aleutians West Census Area", state: "Alaska", type: "Census Area", population: 5504 },
  { name: "Anchorage Municipality", state: "Alaska", type: "Borough", population: 291131 },
  { name: "Bethel Census Area", state: "Alaska", type: "Census Area", population: 18456 },
  { name: "Bristol Bay Borough", state: "Alaska", type: "Borough", population: 844 },
  { name: "Chugach Census Area", state: "Alaska", type: "Census Area", population: 6975 },
  { name: "Copper River Census Area", state: "Alaska", type: "Census Area", population: 2873 },
  { name: "Denali Borough", state: "Alaska", type: "Borough", population: 1980 },
  { name: "Dillingham Census Area", state: "Alaska", type: "Census Area", population: 4708 },
  { name: "Fairbanks North Star Borough", state: "Alaska", type: "Borough", population: 96149 },
  { name: "Haines Borough", state: "Alaska", type: "Borough", population: 2573 },
  { name: "Hoonah-Angoon Census Area", state: "Alaska", type: "Census Area", population: 2073 },
  { name: "Juneau City and Borough", state: "Alaska", type: "Borough", population: 32099 },
  { name: "Kenai Peninsula Borough", state: "Alaska", type: "Borough", population: 58699 },
  { name: "Ketchikan Gateway Borough", state: "Alaska", type: "Borough", population: 13759 },
  { name: "Kodiak Island Borough", state: "Alaska", type: "Borough", population: 12992 },
  { name: "Kusilvak Census Area", state: "Alaska", type: "Census Area", population: 8718 },
  { name: "Lake and Peninsula Borough", state: "Alaska", type: "Borough", population: 1593 },
  { name: "Matanuska-Susitna Borough", state: "Alaska", type: "Borough", population: 110941 },
  { name: "Nome Census Area", state: "Alaska", type: "Census Area", population: 10023 },
  { name: "North Slope Borough", state: "Alaska", type: "Borough", population: 11072 },
  { name: "Northwest Arctic Borough", state: "Alaska", type: "Borough", population: 7775 },
  { name: "Petersburg Borough", state: "Alaska", type: "Borough", population: 3246 },
  { name: "Prince of Wales-Hyder Census Area", state: "Alaska", type: "Census Area", population: 6241 },
  { name: "Sitka City and Borough", state: "Alaska", type: "Borough", population: 8548 },
  { name: "Skagway Municipality", state: "Alaska", type: "Borough", population: 1257 },
  { name: "Southeast Fairbanks Census Area", state: "Alaska", type: "Census Area", population: 6805 },
  { name: "Valdez-Cordova Census Area", state: "Alaska", type: "Census Area", population: 8987 },
  { name: "Wrangell City and Borough", state: "Alaska", type: "Borough", population: 2325 },
  { name: "Yakutat City and Borough", state: "Alaska", type: "Borough", population: 662 },
  { name: "Yukon-Koyukuk Census Area", state: "Alaska", type: "Census Area", population: 5288 }
];

const californiaCounties = [
  { name: "Alameda County", state: "California", type: "County", population: 1656750 },
  { name: "Alpine County", state: "California", type: "County", population: 1104 },
  { name: "Amador County", state: "California", type: "County", population: 40396 },
  { name: "Butte County", state: "California", type: "County", population: 211632 },
  { name: "Calaveras County", state: "California", type: "County", population: 45793 },
  { name: "Colusa County", state: "California", type: "County", population: 21971 },
  { name: "Contra Costa County", state: "California", type: "County", population: 1153526 },
  { name: "Del Norte County", state: "California", type: "County", population: 27817 },
  { name: "El Dorado County", state: "California", type: "County", population: 193698 },
  { name: "Fresno County", state: "California", type: "County", population: 1031800 },
  { name: "Glenn County", state: "California", type: "County", population: 28392 },
  { name: "Humboldt County", state: "California", type: "County", population: 135558 },
  { name: "Imperial County", state: "California", type: "County", population: 184280 },
  { name: "Inyo County", state: "California", type: "County", population: 18039 },
  { name: "Kern County", state: "California", type: "County", population: 919075 },
  { name: "Kings County", state: "California", type: "County", population: 152940 },
  { name: "Lake County", state: "California", type: "County", population: 68363 },
  { name: "Lassen County", state: "California", type: "County", population: 29719 },
  { name: "Los Angeles County", state: "California", type: "County", population: 9881050 },
  { name: "Madera County", state: "California", type: "County", population: 160604 },
  { name: "Marin County", state: "California", type: "County", population: 257774 },
  { name: "Mariposa County", state: "California", type: "County", population: 17131 },
  { name: "Mendocino County", state: "California", type: "County", population: 90008 },
  { name: "Merced County", state: "California", type: "County", population: 286461 },
  { name: "Modoc County", state: "California", type: "County", population: 8641 },
  { name: "Mono County", state: "California", type: "County", population: 14124 },
  { name: "Monterey County", state: "California", type: "County", population: 442049 },
  { name: "Napa County", state: "California", type: "County", population: 137744 },
  { name: "Nevada County", state: "California", type: "County", population: 102909 },
  { name: "Orange County", state: "California", type: "County", population: 3175692 },
  { name: "Placer County", state: "California", type: "County", population: 423748 },
  { name: "Plumas County", state: "California", type: "County", population: 19189 },
  { name: "Riverside County", state: "California", type: "County", population: 2486696 },
  { name: "Sacramento County", state: "California", type: "County", population: 1580664 },
  { name: "San Benito County", state: "California", type: "County", population: 66541 },
  { name: "San Bernardino County", state: "California", type: "County", population: 2233573 },
  { name: "San Diego County", state: "California", type: "County", population: 3327274 },
  { name: "San Francisco County", state: "California", type: "County", population: 815201 },
  { name: "San Joaquin County", state: "California", type: "County", population: 794998 },
  { name: "San Luis Obispo County", state: "California", type: "County", population: 282159 },
  { name: "San Mateo County", state: "California", type: "County", population: 765935 },
  { name: "Santa Barbara County", state: "California", type: "County", population: 448254 },
  { name: "Santa Clara County", state: "California", type: "County", population: 1965683 },
  { name: "Santa Cruz County", state: "California", type: "County", population: 270861 },
  { name: "Shasta County", state: "California", type: "County", population: 182139 },
  { name: "Sierra County", state: "California", type: "County", population: 2895 },
  { name: "Siskiyou County", state: "California", type: "County", population: 43706 },
  { name: "Solano County", state: "California", type: "County", population: 449799 },
  { name: "Sonoma County", state: "California", type: "County", population: 491829 },
  { name: "Stanislaus County", state: "California", type: "County", population: 559220 },
  { name: "Sutter County", state: "California", type: "County", population: 102773 },
  { name: "Tehama County", state: "California", type: "County", population: 66017 },
  { name: "Trinity County", state: "California", type: "County", population: 16047 },
  { name: "Tulare County", state: "California", type: "County", population: 479112 },
  { name: "Tuolumne County", state: "California", type: "County", population: 55285 },
  { name: "Ventura County", state: "California", type: "County", population: 840825 },
  { name: "Yolo County", state: "California", type: "County", population: 224563 },
  { name: "Yuba County", state: "California", type: "County", population: 83715 }
];

const oregonCounties = [
  { name: "Baker County", state: "Oregon", type: "County", population: 16320 },
  { name: "Benton County", state: "Oregon", type: "County", population: 93353 },
  { name: "Clackamas County", state: "Oregon", type: "County", population: 428230 },
  { name: "Clatsop County", state: "Oregon", type: "County", population: 41184 },
  { name: "Columbia County", state: "Oregon", type: "County", population: 52713 },
  { name: "Coos County", state: "Oregon", type: "County", population: 64981 },
  { name: "Crook County", state: "Oregon", type: "County", population: 25455 },
  { name: "Curry County", state: "Oregon", type: "County", population: 23192 },
  { name: "Deschutes County", state: "Oregon", type: "County", population: 205419 },
  { name: "Douglas County", state: "Oregon", type: "County", population: 112901 },
  { name: "Gilliam County", state: "Oregon", type: "County", population: 1845 },
  { name: "Grant County", state: "Oregon", type: "County", population: 7324 },
  { name: "Harney County", state: "Oregon", type: "County", population: 7341 },
  { name: "Hood River County", state: "Oregon", type: "County", population: 24760 },
  { name: "Jackson County", state: "Oregon", type: "County", population: 224537 },
  { name: "Jefferson County", state: "Oregon", type: "County", population: 25557 },
  { name: "Josephine County", state: "Oregon", type: "County", population: 87747 },
  { name: "Klamath County", state: "Oregon", type: "County", population: 69413 },
  { name: "Lake County", state: "Oregon", type: "County", population: 8117 },
  { name: "Lane County", state: "Oregon", type: "County", population: 392606 },
  { name: "Lincoln County", state: "Oregon", type: "County", population: 50959 },
  { name: "Linn County", state: "Oregon", type: "County", population: 131624 },
  { name: "Malheur County", state: "Oregon", type: "County", population: 31185 },
  { name: "Marion County", state: "Oregon", type: "County", population: 352891 },
  { name: "Morrow County", state: "Oregon", type: "County", population: 12500 },
  { name: "Multnomah County", state: "Oregon", type: "County", population: 815428 },
  { name: "Polk County", state: "Oregon", type: "County", population: 87883 },
  { name: "Sherman County", state: "Oregon", type: "County", population: 1795 },
  { name: "Tillamook County", state: "Oregon", type: "County", population: 27090 },
  { name: "Umatilla County", state: "Oregon", type: "County", population: 80280 },
  { name: "Union County", state: "Oregon", type: "County", population: 26490 },
  { name: "Wallowa County", state: "Oregon", type: "County", population: 7071 },
  { name: "Wasco County", state: "Oregon", type: "County", population: 27021 },
  { name: "Washington County", state: "Oregon", type: "County", population: 615801 },
  { name: "Wheeler County", state: "Oregon", type: "County", population: 1371 },
  { name: "Yamhill County", state: "Oregon", type: "County", population: 108160 }
];

const washingtonCounties = [
  { name: "Adams County", state: "Washington", type: "County", population: 20950 },
  { name: "Asotin County", state: "Washington", type: "County", population: 22982 },
  { name: "Benton County", state: "Washington", type: "County", population: 212640 },
  { name: "Chelan County", state: "Washington", type: "County", population: 79774 },
  { name: "Clallam County", state: "Washington", type: "County", population: 77295 },
  { name: "Clark County", state: "Washington", type: "County", population: 518950 },
  { name: "Columbia County", state: "Washington", type: "County", population: 4061 },
  { name: "Cowlitz County", state: "Washington", type: "County", population: 111028 },
  { name: "Douglas County", state: "Washington", type: "County", population: 44856 },
  { name: "Ferry County", state: "Washington", type: "County", population: 7514 },
  { name: "Franklin County", state: "Washington", type: "County", population: 102913 },
  { name: "Garfield County", state: "Washington", type: "County", population: 2335 },
  { name: "Grant County", state: "Washington", type: "County", population: 102738 },
  { name: "Grays Harbor County", state: "Washington", type: "County", population: 76740 },
  { name: "Island County", state: "Washington", type: "County", population: 86732 },
  { name: "Jefferson County", state: "Washington", type: "County", population: 33728 },
  { name: "King County", state: "Washington", type: "County", population: 2306269 },
  { name: "Kitsap County", state: "Washington", type: "County", population: 281330 },
  { name: "Kittitas County", state: "Washington", type: "County", population: 51360 },
  { name: "Klickitat County", state: "Washington", type: "County", population: 23224 },
  { name: "Lewis County", state: "Washington", type: "County", population: 83788 },
  { name: "Lincoln County", state: "Washington", type: "County", population: 10888 },
  { name: "Mason County", state: "Washington", type: "County", population: 67533 },
  { name: "Okanogan County", state: "Washington", type: "County", population: 42424 },
  { name: "Pacific County", state: "Washington", type: "County", population: 23365 },
  { name: "Pend Oreille County", state: "Washington", type: "County", population: 13512 },
  { name: "Pierce County", state: "Washington", type: "County", population: 925700 },
  { name: "San Juan County", state: "Washington", type: "County", population: 18747 },
  { name: "Skagit County", state: "Washington", type: "County", population: 133535 },
  { name: "Skamania County", state: "Washington", type: "County", population: 12103 },
  { name: "Snohomish County", state: "Washington", type: "County", population: 880330 },
  { name: "Spokane County", state: "Washington", type: "County", population: 554791 },
  { name: "Stevens County", state: "Washington", type: "County", population: 47873 },
  { name: "Thurston County", state: "Washington", type: "County", population: 303976 },
  { name: "Wahkiakum County", state: "Washington", type: "County", population: 4626 },
  { name: "Walla Walla County", state: "Washington", type: "County", population: 61874 },
  { name: "Whatcom County", state: "Washington", type: "County", population: 240770 },
  { name: "Whitman County", state: "Washington", type: "County", population: 49918 },
  { name: "Yakima County", state: "Washington", type: "County", population: 261247 }
];

const idahoCounties = [
  { name: "Ada County", state: "Idaho", type: "County", population: 522180 },
  { name: "Adams County", state: "Idaho", type: "County", population: 4297 },
  { name: "Bannock County", state: "Idaho", type: "County", population: 89155 },
  { name: "Bear Lake County", state: "Idaho", type: "County", population: 6396 },
  { name: "Benewah County", state: "Idaho", type: "County", population: 9845 },
  { name: "Bingham County", state: "Idaho", type: "County", population: 47475 },
  { name: "Blaine County", state: "Idaho", type: "County", population: 24495 },
  { name: "Boise County", state: "Idaho", type: "County", population: 7748 },
  { name: "Bonner County", state: "Idaho", type: "County", population: 50190 },
  { name: "Bonneville County", state: "Idaho", type: "County", population: 127878 },
  { name: "Boundary County", state: "Idaho", type: "County", population: 12727 },
  { name: "Butte County", state: "Idaho", type: "County", population: 2562 },
  { name: "Camas County", state: "Idaho", type: "County", population: 1102 },
  { name: "Canyon County", state: "Idaho", type: "County", population: 248922 },
  { name: "Caribou County", state: "Idaho", type: "County", population: 7559 },
  { name: "Cassia County", state: "Idaho", type: "County", population: 25018 },
  { name: "Clark County", state: "Idaho", type: "County", population: 860 },
  { name: "Clearwater County", state: "Idaho", type: "County", population: 8855 },
  { name: "Custer County", state: "Idaho", type: "County", population: 4328 },
  { name: "Elmore County", state: "Idaho", type: "County", population: 28500 },
  { name: "Franklin County", state: "Idaho", type: "County", population: 15379 },
  { name: "Fremont County", state: "Idaho", type: "County", population: 13487 },
  { name: "Gem County", state: "Idaho", type: "County", population: 20623 },
  { name: "Gooding County", state: "Idaho", type: "County", population: 15540 },
  { name: "Idaho County", state: "Idaho", type: "County", population: 16791 },
  { name: "Jefferson County", state: "Idaho", type: "County", population: 32058 },
  { name: "Jerome County", state: "Idaho", type: "County", population: 25736 },
  { name: "Kootenai County", state: "Idaho", type: "County", population: 182617 },
  { name: "Latah County", state: "Idaho", type: "County", population: 40791 },
  { name: "Lemhi County", state: "Idaho", type: "County", population: 8200 },
  { name: "Lewis County", state: "Idaho", type: "County", population: 3983 },
  { name: "Lincoln County", state: "Idaho", type: "County", population: 5636 },
  { name: "Madison County", state: "Idaho", type: "County", population: 52667 },
  { name: "Minidoka County", state: "Idaho", type: "County", population: 24016 },
  { name: "Nez Perce County", state: "Idaho", type: "County", population: 43284 },
  { name: "Oneida County", state: "Idaho", type: "County", population: 4813 },
  { name: "Owyhee County", state: "Idaho", type: "County", population: 12264 },
  { name: "Payette County", state: "Idaho", type: "County", population: 25282 },
  { name: "Power County", state: "Idaho", type: "County", population: 8001 },
  { name: "Shoshone County", state: "Idaho", type: "County", population: 13001 },
  { name: "Teton County", state: "Idaho", type: "County", population: 12467 },
  { name: "Twin Falls County", state: "Idaho", type: "County", population: 96122 },
  { name: "Valley County", state: "Idaho", type: "County", population: 11847 },
  { name: "Washington County", state: "Idaho", type: "County", population: 10949 }
];


const nevadaCounties = [
  { name: "Carson City", state: "Nevada", type: "Independent City", population: 58372 },
  { name: "Churchill County", state: "Nevada", type: "County", population: 25616 },
  { name: "Clark County", state: "Nevada", type: "County", population: 2342804 },
  { name: "Douglas County", state: "Nevada", type: "County", population: 49488 },
  { name: "Elko County", state: "Nevada", type: "County", population: 54558 },
  { name: "Esmeralda County", state: "Nevada", type: "County", population: 851 },
  { name: "Eureka County", state: "Nevada", type: "County", population: 2071 },
  { name: "Humboldt County", state: "Nevada", type: "County", population: 18053 },
  { name: "Lander County", state: "Nevada", type: "County", population: 5902 },
  { name: "Lincoln County", state: "Nevada", type: "County", population: 4995 },
  { name: "Lyon County", state: "Nevada", type: "County", population: 62303 },
  { name: "Mineral County", state: "Nevada", type: "County", population: 4415 },
  { name: "Nye County", state: "Nevada", type: "County", population: 53660 },
  { name: "Pershing County", state: "Nevada", type: "County", population: 6771 },
  { name: "Storey County", state: "Nevada", type: "County", population: 4290 },
  { name: "Washoe County", state: "Nevada", type: "County", population: 499202 },
  { name: "White Pine County", state: "Nevada", type: "County", population: 9485 }
];

const arizonaCounties = [
  { name: "Apache County", state: "Arizona", type: "County", population: 66168 },
  { name: "Cochise County", state: "Arizona", type: "County", population: 126739 },
  { name: "Coconino County", state: "Arizona", type: "County", population: 150849 },
  { name: "Gila County", state: "Arizona", type: "County", population: 52951 },
  { name: "Graham County", state: "Arizona", type: "County", population: 39405 },
  { name: "Greenlee County", state: "Arizona", type: "County", population: 9537 },
  { name: "La Paz County", state: "Arizona", type: "County", population: 16486 },
  { name: "Maricopa County", state: "Arizona", type: "County", population: 4624867 },
  { name: "Mohave County", state: "Arizona", type: "County", population: 217985 },
  { name: "Navajo County", state: "Arizona", type: "County", population: 107656 },
  { name: "Pima County", state: "Arizona", type: "County", population: 1036730 },
  { name: "Pinal County", state: "Arizona", type: "County", population: 496588 },
  { name: "Santa Cruz County", state: "Arizona", type: "County", population: 47848 },
  { name: "Yavapai County", state: "Arizona", type: "County", population: 242253 },
  { name: "Yuma County", state: "Arizona", type: "County", population: 224047 }
];


